### ISSUE TITLE
Tickets that have been submitted and paid are not showing in the list.

### ISSUE THREAD

**Issue by rleed** [lnbits/lnticket#4]
To reproduce: install the extension. Add a form (I used a newly created wallet, gave a name and description, and specified 1 sat per word). After creating the form, go to the link provided. Enter some test data and submit the form. Pay the invoice. After successful payment, go back to the LNbits wallet. The wallet shows the transaction, but the Support Tickets extension does not list any tickets.

**Comment by talvasconcelos** [comment]
Does this still happen? did you refresh the tickets page?
